openapi: 3.1.0
info:
  title: Aster API
  version: 1.0.0
  description: API documentation for the Aster task manager.

servers:
  - url: http://localhost:3000/api

paths:

  ########################
  # AUTH
  ########################
  /auth/register:
    post:
      tags: [Auth]
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterInput"
            example:
              name: "Greyson Brummer"
              email: "greyson@example.com"
              password: "SuperSecret123!"
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                id: 1
                name: "Greyson Brummer"
                email: "greyson@example.com"

  /auth/login:
    post:
      tags: [Auth]
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginInput"
            example:
              email: "greyson@example.com"
              password: "SuperSecret123!"
      responses:
        200:
          description: Login success
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
              example:
                token: "jwt_token_value"

  /auth/me:
    get:
      tags: [Auth]
      summary: Get current authenticated user
      responses:
        200:
          description: User info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                id: 1
                name: "Greyson Brummer"
                email: "greyson@example.com"



  ########################
  # USERS
  ########################
  /users:
    get:
      tags: [Users]
      summary: Get all users
      responses:
        200:
          description: List of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
              example:
                - id: 1
                  name: "Greyson Brummer"
                  email: "greyson@example.com"
                - id: 2
                  name: "Alex Smith"
                  email: "alex@example.com"

    post:
      tags: [Users]
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterInput"
            example:
              name: "New User"
              email: "newuser@example.com"
              password: "Password123!"
      responses:
        201:
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                id: 5
                name: "New User"
                email: "newuser@example.com"

  /users/{id}:
    get:
      tags: [Users]
      summary: Get user by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: User found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                id: 1
                name: "Greyson Brummer"
                email: "greyson@example.com"

    put:
      tags: [Users]
      summary: Update user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUser"
            example:
              name: "Updated Name"
              email: "updated@example.com"
      responses:
        200:
          description: User updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                id: 1
                name: "Updated Name"
                email: "updated@example.com"

    delete:
      tags: [Users]
      summary: Delete user
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: User deleted



  ########################
  # TASKS
  ########################
  /tasks:
    get:
      tags: [Tasks]
      summary: Get all tasks
      responses:
        200:
          description: Task list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
              example:
                - id: 1
                  title: "Finish Aster API"
                  completed: false
                  userId: 1
                - id: 2
                  title: "Study Security+"
                  completed: true
                  userId: 1

    post:
      tags: [Tasks]
      summary: Create new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTask"
            example:
              title: "Write documentation"
              completed: false
              userId: 1
      responses:
        201:
          description: Task created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 10
                title: "Write documentation"
                completed: false
                userId: 1

  /tasks/{id}:
    get:
      tags: [Tasks]
      summary: Get task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Task found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: "Finish Aster API"
                completed: false
                userId: 1

    put:
      tags: [Tasks]
      summary: Update task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTask"
            example:
              title: "Updated Task"
              completed: true
      responses:
        200:
          description: Task updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
              example:
                id: 1
                title: "Updated Task"
                completed: true
                userId: 1

    delete:
      tags: [Tasks]
      summary: Delete task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Task deleted



  ########################
  # CATEGORIES
  ########################
  /categories:
    get:
      tags: [Categories]
      summary: Get all categories
      responses:
        200:
          description: Category list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
              example:
                - id: 1
                  name: "Work"
                - id: 2
                  name: "Personal"

    post:
      tags: [Categories]
      summary: Create category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategory"
            example:
              name: "Fitness"
      responses:
        201:
          description: Category created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
              example:
                id: 3
                name: "Fitness"

  /categories/{id}:
    put:
      tags: [Categories]
      summary: Update category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateCategory"
            example:
              name: "Updated Category"
      responses:
        200:
          description: Category updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
              example:
                id: 1
                name: "Updated Category"

    delete:
      tags: [Categories]
      summary: Delete category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Category deleted



  ########################
  # TAGS
  ########################
  /tags:
    get:
      tags: [Tags]
      summary: Get all tags
      responses:
        200:
          description: Tag list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tag"
              example:
                - id: 1
                  name: "urgent"
                - id: 2
                  name: "school"

    post:
      tags: [Tags]
      summary: Create tag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTag"
            example:
              name: "priority"
      responses:
        201:
          description: Tag created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tag"
              example:
                id: 3
                name: "priority"

  /tags/{id}:
    delete:
      tags: [Tags]
      summary: Delete tag
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Tag deleted



########################
# COMPONENTS
########################
components:
  schemas:

    ######## AUTH ########
    RegisterInput:
      type: object
      properties:
        name: { type: string }
        email: { type: string }
        password: { type: string }
      required: [name, email, password]

    LoginInput:
      type: object
      properties:
        email: { type: string }
        password: { type: string }
      required: [email, password]


    ######## USERS ########
    User:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }
        email: { type: string }

    UpdateUser:
      type: object
      properties:
        name: { type: string }
        email: { type: string }


    ######## TASKS ########
    Task:
      type: object
      properties:
        id: { type: integer }
        title: { type: string }
        completed: { type: boolean }
        userId: { type: integer }

    CreateTask:
      type: object
      properties:
        title: { type: string }
        completed: { type: boolean }
        userId: { type: integer }
      required: [title, completed, userId]

    UpdateTask:
      type: object
      properties:
        title: { type: string }
        completed: { type: boolean }


    ######## CATEGORIES ########
    Category:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }

    CreateCategory:
      type: object
      properties:
        name: { type: string }
      required: [name]


    ######## TAGS ########
    Tag:
      type: object
      properties:
        id: { type: integer }
        name: { type: string }

    CreateTag:
      type: object
      properties:
        name: { type: string }
      required: [name]














